export const colleges = [
  { name: 'Indian Institute of Technology (IIT) Bombay', location: 'Mumbai, Maharashtra', fees: 220000, rating: 4.9, description: 'Premier engineering institute known for its excellent placements and campus life.', placement_percentage: 95, courses: [{ name: 'B.Tech Computer Science', duration: '4 Years' }, { name: 'M.Tech Data Science', duration: '2 Years' }] },
  { name: 'Indian Institute of Technology (IIT) Delhi', location: 'New Delhi, Delhi', fees: 215000, rating: 4.8, description: 'Leading institute in research and engineering studies with strong industry connections.', placement_percentage: 94, courses: [{ name: 'B.Tech Electrical Engineering', duration: '4 Years' }] },
  { name: 'National Institute of Technology (NIT) Trichy', location: 'Tiruchirappalli, Tamil Nadu', fees: 150000, rating: 4.7, description: 'Top-ranked NIT offering high-quality education and excellent ROI.', placement_percentage: 92, courses: [{ name: 'B.Tech Mechanical Engineering', duration: '4 Years' }] },
  { name: 'Birla Institute of Technology and Science (BITS)', location: 'Pilani, Rajasthan', fees: 450000, rating: 4.8, description: 'Highly reputed private institution with zero attendance policy and brilliant alumni.', placement_percentage: 96, courses: [{ name: 'B.E. Computer Science', duration: '4 Years' }, { name: 'B.E. Electronics', duration: '4 Years' }] },
  { name: 'Vellore Institute of Technology (VIT)', location: 'Vellore, Tamil Nadu', fees: 198000, rating: 4.2, description: 'Known for its massive campus, diverse student body, and strong IT placements.', placement_percentage: 85, courses: [{ name: 'B.Tech Information Technology', duration: '4 Years' }] },
  { name: 'Delhi Technological University (DTU)', location: 'New Delhi, Delhi', fees: 166000, rating: 4.5, description: 'Formerly DCE, famous for exceptional tech culture and massive tech placements.', placement_percentage: 90, courses: [{ name: 'B.Tech Software Engineering', duration: '4 Years' }] },
  { name: 'SRM Institute of Science and Technology', location: 'Chennai, Tamil Nadu', fees: 250000, rating: 4.0, description: 'Large multi-stream university with vast infrastructure and global tie-ups.', placement_percentage: 82, courses: [{ name: 'B.Tech CSE', duration: '4 Years' }] },
  { name: 'Manipal Institute of Technology (MIT)', location: 'Manipal, Karnataka', fees: 335000, rating: 4.3, description: 'Vibrant college life, state-of-the-art facilities, and strong alumni network.', placement_percentage: 84, courses: [{ name: 'B.Tech Aeronautical', duration: '4 Years' }] },
  { name: 'College of Engineering, Pune (COEP)', location: 'Pune, Maharashtra', fees: 90000, rating: 4.6, description: 'One of the oldest engineering colleges in Asia with excellent academics.', placement_percentage: 88, courses: [{ name: 'B.Tech Instrumentation', duration: '4 Years' }] },
  { name: 'Indian Institute of Technology (IIT) Madras', location: 'Chennai, Tamil Nadu', fees: 210000, rating: 4.9, description: 'Top ranked engineering college in India consistently by NIRF.', placement_percentage: 93, courses: [{ name: 'B.Tech Aerospace', duration: '4 Years' }] },
];
